import MessageBox from "@/components/MessageBox";
import PageWrapper from "@/components/PageWrapper";
import DealerBoard from "@/containers/DealerBoard";
import Deck from "@/containers/Deck";
import GameDecisions from "@/containers/GameDecisions";
import PlayerBoard from "@/containers/PlayerBoard";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Black Jack Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </Head>
      <PageWrapper>
        <MessageBox />
        <DealerBoard />
        <Deck />
        <PlayerBoard />
        <GameDecisions />
      </PageWrapper>
    </>
  );
};

export default Home;
